### ISSUE TITLE
Switch IME Error: Get current input source faild

### ISSUE THREAD

**Issue by Camio1945** [rieonke/idea-auto-switch-im#1]
windows7获取不到输入法，报错：
Switch IME Error: Get current input source faild
![image](https://user-images.githubusercontent.com/7963197/28100951-e89c3a80-66f7-11e7-91d2-2a19a79b09a3.png)

**Comment by rieonke** [comment]
你好 这个暂时不支持Windows，目前支持macOS。Windows的适配正在实现，欢迎Pull Request
