### ISSUE TITLE
报错，取不到输入法

### ISSUE THREAD

**Issue by HalfLegend** [rieonke/idea-auto-switch-im#5]
每次进入vim模式报错:   Get current input source faild

并且在plugin的设置中，取不到输入法列表

**Comment by rieonke** [comment]
麻烦提供一下你的操作系统和IDE版本。

**Comment by HalfLegend** [comment]
不好意思 可以关单了 我重启了一下ide 就正常了

您的插件真的很好用

**Comment by HalfLegend** [comment]
可以关单了 重启idea后好了…
不好意思 打扰了

您这个插件真的很好用

在 2018年5月2日，20:09，Rieon <notifications@github.com<mailto:notifications@github.com>> 写道：


麻烦提供一下你的操作系统和IDE版本。

**Comment by rieonke** [comment]
谢谢！
